# Generated by Django 5.1.1 on 2024-10-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="course",
        ),
        migrations.AddField(
            model_name="program",
            name="courses",
            field=models.CharField(default="My Course", max_length=500),
            preserve_default=False,
        ),
    ]
