# Generated by Django 5.0 on 2024-10-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_remove_student_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_profile",
            name="profile_image",
            field=models.ImageField(
                default="student_profile/handsome-bearded-guy.jpg",
                upload_to="student_profile",
            ),
            preserve_default=False,
        ),
    ]
