# Generated by Django 5.0 on 2024-10-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_alter_student_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_profile",
            name="profile_image",
            field=models.ImageField(
                default="student_profile/handsome-bearded-guy.jpg",
                null=True,
                upload_to="student_profile",
            ),
        ),
    ]
