# Generated by Django 5.0 on 2024-10-21 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_cohortgroup_date_join_student_student_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_join",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
