# Generated by Django 5.0 on 2024-10-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_student_date_join"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["-date_join"]},
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
            ),
        ),
    ]
