# Generated by Django 5.0 on 2024-10-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0014_alter_student_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_type",
            field=models.CharField(
                choices=[
                    ("Cohort Leader", "cohort leader"),
                    ("Deputy Leader", "vice leader"),
                    ("Secretary", "secretary"),
                    ("President", "President"),
                    ("Member", "member"),
                ],
                default="member",
                max_length=100,
            ),
        ),
    ]
