# Generated by Django 5.0 on 2024-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0015_alter_student_student_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_type",
            field=models.CharField(
                choices=[
                    ("leader", "cohort leader"),
                    ("deputy", "vice leader"),
                    ("secretary", "secretary"),
                    ("President", "President"),
                    ("member", "member"),
                ],
                default="member",
                max_length=100,
            ),
        ),
    ]
