# Generated by Django 5.0 on 2024-10-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0016_alter_student_student_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("Active", "active"), ("Inactive", "inactive")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_type",
            field=models.CharField(
                choices=[
                    ("Cohort Leader", "leader"),
                    ("Vice Leader", "deputy"),
                    ("Secretary", "secretary"),
                    ("President", "president"),
                    ("Member", "member"),
                ],
                default="member",
                max_length=100,
            ),
        ),
    ]
